import Head from "next/head";
import Image from "next/image";
import { useFormik } from "formik";
import { useRouter } from "next/router";
import * as Yup from "yup";
import { motion } from "framer-motion";

import formImage from "../public/form.png";
import InputField from "../components/InputField";
import SelectField from "../components/SelectField";
import TermsOfService from "../components/TermsOfService";

const siteTitle = "Next.js Form";

export default function Home() {
  const countries = [
    "United States",
    "Canada",
    "United Kingdom",
    "France",
    "Germany",
    "Norway",
  ];

  // Next.js Router
  const router = useRouter();

  // Formic Logics
  const formik = useFormik({
    initialValues: {
      name: "",
      email: "",
      country: countries[0],
      terms: [],
    },

    validationSchema: Yup.object({
      name: Yup.string()
        .min(2, "Name must be 2 characters or more.")
        .max(20, "Name must be 20 characters or less.")
        .required("Name is required"),
      email: Yup.string()
        .email("Invalid email address.")
        .required("Email is required"),
      terms: Yup.array()
        .length(1, "Terms of service must be checked.")
        .required("Terms of service must be checked."),
    }),

    onSubmit: (values) => {
      console.log(values);
      router.push({
        pathname: "/success",
        query: values,
      });
    },
  });

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
    >
      <Head>
        <title>{siteTitle}</title>
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content="Generated by create next app" />
        <meta
          property="og:image"
          content={`https://og-image.vercel.app/${encodeURI(
            siteTitle
          )}.png?theme=dark&md=0&fontSize=75px&images=https%3A%2F%2Fassets.vercel.com%2Fimage%2Fupload%2Ffront%2Fassets%2Fdesign%2Fnextjs-white-logo.svg`}
        />
        <meta name="og:title" content={siteTitle} />
        <meta name="twitter:card" content="summary_large_image" />
      </Head>

      <main className="min-h-screen flex items-center justify-center py-8 laptop:py-0">
        <form
          onSubmit={formik.handleSubmit}
          className="bg-white flex rounded-lg w-[min(100%,_1024px)] font-latoRegular laptop:w-full laptop:min-h-screen laptop:rounded-none"
        >
          <div className="flex-1 text-gray-700 p-20 laptop:flex laptop:flex-col laptop:justify-center laptop:p-16 mobile:px-10">
            <h1 className="text-3xl pb-2 font-latoBold">
              Let&apos;s get started 👋
            </h1>
            <p className="text-lg text-gray-500">
              Join our E-learning platform today and unlock over 500+ courses
              and digital assets ready to download.
            </p>

            <div className="mt-6">
              {/* Name Input Field */}
              <InputField
                id="name"
                label="Name"
                value={formik.values.name}
                placeholder="Enter your name"
                onChange={formik.handleChange}
                onBlur={formik.handleBlur}
                errorMessage={formik.errors.name}
                touched={formik.touched.name}
              />
              {/* Email Input Field */}
              <InputField
                id="email"
                type="email"
                label="Email"
                value={formik.values.email}
                placeholder="Enter your email"
                onChange={formik.handleChange}
                onBlur={formik.handleBlur}
                errorMessage={formik.errors.email}
                touched={formik.touched.email}
              />
              <SelectField
                id="country"
                label="Country"
                options={countries}
                value={formik.values.country}
                onChange={formik.handleChange}
              />
              <TermsOfService
                onChange={formik.handleChange}
                errorMessage={formik.errors.terms}
                touched={formik.touched.terms}
              />
            </div>

            <button
              type="submit"
              disabled={Boolean(
                !formik.values.name ||
                  formik.errors.name ||
                  !formik.values.email ||
                  formik.errors.email ||
                  formik.errors.terms
              )}
              className="bg-teal-500 font-latoBold text-sm text-white py-3 mt-6 rounded-lg w-full hover:bg-teal-600 disabled:bg-teal-400 disabled:cursor-not-allowed"
            >
              Start learning totay!
            </button>
          </div>

          <div className="flex-1 relative tablet:hidden">
            <Image
              src={formImage}
              alt="form-learn"
              fill
              priority
              sizes="100%"
              className="object-cover rounded-lg laptop:rounded-none"
            />
          </div>
        </form>
      </main>
    </motion.div>
  );
}
